# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DejaVu < Formula
  desc "Persistent memory for your coding agents"
  homepage "https://github.com/vshulcz/deja-vu"
  version "0.16.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vshulcz/deja-vu/releases/download/v0.16.9/deja-vu_0.16.9_darwin_amd64.tar.gz"
      sha256 "4d5e5f016196f15c35c7f2859bfa0251fafef4904091bb899deadfb1807acb74"

      define_method(:install) do
        bin.install "deja"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vshulcz/deja-vu/releases/download/v0.16.9/deja-vu_0.16.9_darwin_arm64.tar.gz"
      sha256 "db8288ebd65e48b2a5fc7bb5dea9f870920fde4d5b58bf0ba2c2cf1c2a1d6453"

      define_method(:install) do
        bin.install "deja"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshulcz/deja-vu/releases/download/v0.16.9/deja-vu_0.16.9_linux_amd64.tar.gz"
      sha256 "f2e4be3e93d90991ab91f16277f1f0fee7f24db97d50f10ee8fdc35a2c14601a"
      define_method(:install) do
        bin.install "deja"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshulcz/deja-vu/releases/download/v0.16.9/deja-vu_0.16.9_linux_arm64.tar.gz"
      sha256 "ac3a4341c33e429120831f246bf9b9b4945e4173d2ef0c8b37752d9964c6a32d"
      define_method(:install) do
        bin.install "deja"
      end
    end
  end
end
