# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DejaVu < Formula
  desc "Persistent memory for your coding agents"
  homepage "https://github.com/vshulcz/deja-vu"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vshulcz/deja-vu/releases/download/v0.1.0/deja-vu_0.1.0_darwin_amd64.tar.gz"
      sha256 "797c48383005eac27ba1b26a279f7b9025b073c3703530d592a50b0c3d3dafa1"

      define_method(:install) do
        bin.install "deja"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vshulcz/deja-vu/releases/download/v0.1.0/deja-vu_0.1.0_darwin_arm64.tar.gz"
      sha256 "de7d88741284f74b028af6b9cbdb66b1cde0f40c7e2827ad4626d334b2f11102"

      define_method(:install) do
        bin.install "deja"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshulcz/deja-vu/releases/download/v0.1.0/deja-vu_0.1.0_linux_amd64.tar.gz"
      sha256 "aa59dc51756cfe937c4cd83a3a36bc2dd70917848fbafe6bb6a98bcf4e44c2fc"
      define_method(:install) do
        bin.install "deja"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshulcz/deja-vu/releases/download/v0.1.0/deja-vu_0.1.0_linux_arm64.tar.gz"
      sha256 "30363742c6b2128b11931c2911ceb927703f1b029692407fca23c46d95f762eb"
      define_method(:install) do
        bin.install "deja"
      end
    end
  end
end
